language: python
python:
    - "2.7"
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
before_install:
    - sudo apt-get update
    - "pip install -U setuptools"
install:
    - python bootstrap.py
    - ./bin/buildout
script: ./bin/test
notifications:
    email:
        on_success: never
        on_failure: change
