language: python
python:
    - "2.7"
before_install:
    - "pip install -U setuptools"
    - sudo apt-get -f install python-pyside
install:
    - python bootstrap.py
    - ./bin/buildout
script: ./bin/test
notifications:
    email:
        on_success: never
        on_failure: change
