language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update
    - sudo apt-get -f install python-pyside
    - "pip install -U setuptools"
install:
    - python bootstrap.py
    - ./bin/buildout
script: ./bin/test
notifications:
    email:
        on_success: never
        on_failure: change
